import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Overview</span>',
    },
    { type: "autogenerated", dirName: "overview" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Getting Started</span>',
    },
    { type: "autogenerated", dirName: "getting_started" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Core Concepts</span>',
    },
    { type: "autogenerated", dirName: "core_concepts" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">API & SDKs</span>',
    },
    { type: "autogenerated", dirName: "api" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Integrations</span>',
    },
    { type: "autogenerated", dirName: "integration" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Tutorials & examples</span>',
    },
    { type: "autogenerated", dirName: "tutorials" },
    {
      type: "html",
      value:
        '<span class="block p-2 font-semibold underline cursor-default text-orange-950">Reference</span>',
    },
    { type: "autogenerated", dirName: "reference" },
    {
      type: "link",
      label: "Rust Docs",
      href: "https://rust.haste.health",
    },
    {
      type: "link",
      label: "Typescript Docs",
      href: "https://typescript.haste.health",
    },
  ],

  rfcSidebar: [
    {
      type: "autogenerated",
      dirName: "rfc",
    },
  ],
};

export default sidebars;
