services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2-arm64
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.ml.use_auto_machine_memory_percent=true
      - ES_JAVA_OPTS=-Xms128m -Xmx2g
      - cluster.routing.allocation.disk.watermark.low=1gb
      - cluster.routing.allocation.disk.watermark.high=1gb
      - cluster.routing.allocation.disk.watermark.flood_stage=1gb
      - "_JAVA_OPTIONS=-XX:UseSVE=0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --output /dev/null --silent --head --fail -u elastic:elastic http://elasticsearch:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 30

  postgres:
    image: postgres:18.1
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DB=haste_health
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  hastehealth-migrate:
    image: ghcr.io/hastehealth/hastehealth/hastehealth:latest
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    entrypoint: ["/bin/bash"]
    command:
      - /haste-health server migrate all && /haste-health server tenant create --id=my-health '--owner-email=myuser@health.org' --owner-password=testing_password --subscription-tier=unlimited

    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/haste_health
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
  hastehealth-server:
    image: ghcr.io/hastehealth/hastehealth/hastehealth:latest
    platform: linux/amd64
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch: 
        condition: service_healthy
    command:
      - server
      - start
    environment:
      - CERTIFICATION_DIR=certifications
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/haste_health
      - API_URI=http://localhost:3000
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - ADMIN_APP_REDIRECT_URI=http://*.localhost:3001
    
  hastehealth-worker:
    image: ghcr.io/hastehealth/hastehealth/hastehealth:latest
    platform: linux/amd64
    command:
      - worker
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch: 
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/haste_health
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic

  hastehealth-admin-app:
    image: ghcr.io/hastehealth/hastehealth/admin-app:latest
    platform: linux/amd64
    ports:
      - 3001:80
    depends_on:
      - hastehealth-worker
      - hastehealth-server
    environment:
      - REACT_APP_FHIR_BASE_URL=http://localhost:3000
    