use deno_core::cppgc::GcCell;
use deno_core::error::ModuleLoaderError;

use deno_core::{
    Extension, GarbageCollected, ModuleLoadOptions, ModuleLoadReferrer, ModuleLoader, ModuleSource,
    ModuleType, OpState, op2, resolve_import, serde_json, v8,
};
// main.rs
use deno_core::error::AnyError;
use haste_fhir_client::FHIRClient;
use haste_fhir_client::http::{FHIRHttpClient, FHIRHttpState};
use haste_fhir_model::r4::generated::resources::ResourceType;
use haste_fhir_operation_error::OperationOutcomeError;
use std::cell::RefCell;
use std::rc::Rc;
use std::sync::Arc;

use deno_ast::{MediaType, ModuleSpecifier};
use deno_ast::{ParseParams, SourceMapOption};
use deno_core::ModuleLoadResponse;
use deno_core::ModuleSourceCode;
use deno_error::JsErrorBox;

// Load the snapshot generated by build.rs:
static RUNTIME_SNAPSHOT: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/RUNJS_SNAPSHOT.bin"));

struct TsModuleLoader;
impl ModuleLoader for TsModuleLoader {
    fn resolve(
        &self,
        specifier: &str,
        referrer: &str,
        _kind: deno_core::ResolutionKind,
    ) -> Result<deno_core::ModuleSpecifier, ModuleLoaderError> {
        resolve_import(specifier, referrer).map_err(JsErrorBox::from_err)
    }

    fn load(
        &self,
        module_specifier: &ModuleSpecifier,
        _maybe_referrer: Option<&ModuleLoadReferrer>,
        _options: ModuleLoadOptions,
    ) -> ModuleLoadResponse {
        fn load(module_specifier: &ModuleSpecifier) -> Result<ModuleSource, ModuleLoaderError> {
            let path = module_specifier
                .to_file_path()
                .map_err(|_| JsErrorBox::generic("Only file:// URLs are supported."))?;

            let media_type = MediaType::from_path(&path);
            let (module_type, should_transpile) = match MediaType::from_path(&path) {
                MediaType::JavaScript | MediaType::Mjs | MediaType::Cjs => {
                    (ModuleType::JavaScript, false)
                }
                MediaType::Jsx => (ModuleType::JavaScript, true),
                MediaType::TypeScript
                | MediaType::Mts
                | MediaType::Cts
                | MediaType::Dts
                | MediaType::Dmts
                | MediaType::Dcts
                | MediaType::Tsx => (ModuleType::JavaScript, true),
                MediaType::Json => (ModuleType::Json, false),
                _ => {
                    return Err(JsErrorBox::generic(format!(
                        "Unknown extension {:?}",
                        path.extension()
                    )));
                }
            };

            let code = std::fs::read_to_string(&path).map_err(JsErrorBox::from_err)?;
            let code = if should_transpile {
                let parsed = deno_ast::parse_module(ParseParams {
                    specifier: module_specifier.clone(),
                    text: code.into(),
                    media_type,
                    capture_tokens: false,
                    scope_analysis: false,
                    maybe_syntax: None,
                })
                .map_err(JsErrorBox::from_err)?;
                let res = parsed
                    .transpile(
                        &deno_ast::TranspileOptions {
                            imports_not_used_as_values: deno_ast::ImportsNotUsedAsValues::Remove,
                            decorators: deno_ast::DecoratorsTranspileOption::Ecma,
                            ..Default::default()
                        },
                        &deno_ast::TranspileModuleOptions { module_kind: None },
                        &deno_ast::EmitOptions {
                            source_map: SourceMapOption::Separate,
                            inline_sources: true,
                            ..Default::default()
                        },
                    )
                    .map_err(JsErrorBox::from_err)?;
                let res = res.into_source();
                // let source_map = res.source_map.unwrap().into_bytes();

                res.text
            } else {
                code
            };
            Ok(ModuleSource::new(
                module_type,
                ModuleSourceCode::String(code.into()),
                module_specifier,
                None,
            ))
        }

        ModuleLoadResponse::Sync(load(module_specifier))
    }
}

struct AppState<CTX, Client: FHIRClient<CTX, OperationOutcomeError>> {
    fhir_client: Arc<Client>,
    ctx: CTX,
}

#[repr(C)]
pub struct InteropObject {
    value: GcCell<f64>,
}

unsafe impl GarbageCollected for InteropObject {
    fn trace(&self, _visitor: &mut v8::cppgc::Visitor) {}
    fn get_name(&self) -> &'static std::ffi::CStr {
        c"InteropObject"
    }
}

#[op2]
impl InteropObject {
    #[constructor]
    #[cppgc]
    fn new(value: f64) -> InteropObject {
        InteropObject {
            value: GcCell::new(value),
        }
    }

    #[getter]
    fn value(&self, isolate: &v8::Isolate) -> f64 {
        *self.value.get(isolate)
    }

    #[setter]
    fn value(&self, isolate: &mut v8::Isolate, value: f64) {
        self.value.set(isolate, value);
    }

    // #[fast]
    // fn double_value(&self, isolate: &v8::Isolate) -> f64 {
    //     *self.value.get(isolate) * 2.0
    // }

    #[static_method]
    #[cppgc]
    fn create(value: f64) -> InteropObject {
        InteropObject {
            value: GcCell::new(value),
        }
    }
}

#[op2]
#[serde]
pub async fn read_resource<
    CTX: Clone + 'static,
    Client: FHIRClient<CTX, OperationOutcomeError> + 'static,
>(
    state: Rc<RefCell<OpState>>,
    #[string] resource_type: String,
    #[string] id: String,
) -> Result<serde_json::Value, deno_error::JsErrorBox> {
    let state = state.borrow();
    // Use the state

    let app_state = state.borrow::<Arc<AppState<CTX, Client>>>();

    let patient = app_state
        .fhir_client
        .read(
            app_state.ctx.clone(),
            ResourceType::try_from(resource_type)
                .map_err(|_| deno_error::JsErrorBox::type_error("Invalid resource type"))?,
            id,
        )
        .await
        .map_err(|_| deno_error::JsErrorBox::type_error("Failed to read resource"))?;

    serde_json::from_str(&haste_fhir_serialization_json::to_string(&patient).unwrap())
        .map_err(|_| deno_error::JsErrorBox::type_error("Failed to serialize resource"))
}

async fn run_js<CTX: Clone + 'static, Client: FHIRClient<CTX, OperationOutcomeError> + 'static>(
    ctx: CTX,
    client: Client,
    file_path: &str,
) -> Result<(), AnyError> {
    let main_module = deno_core::resolve_path(file_path, &std::env::current_dir()?)?;

    let runjs = Extension {
        name: "runjs",
        ops: std::borrow::Cow::Owned(vec![read_resource::<CTX, Client>()]),
        ..Default::default()
    };

    let mut js_runtime = deno_core::JsRuntime::new(deno_core::RuntimeOptions {
        module_loader: Some(Rc::new(TsModuleLoader)),
        extensions: vec![runjs],
        startup_snapshot: Some(RUNTIME_SNAPSHOT),
        // startup_snapshot: Some(RUNTIME_SNAPSHOT),
        ..Default::default()
    });

    {
        let op_state = js_runtime.op_state();
        let mut op_state = op_state.borrow_mut();
        op_state.put(Arc::new(AppState {
            fhir_client: Arc::new(client),
            ctx,
        }));
    }

    let mod_id = js_runtime.load_main_es_module(&main_module).await?;
    let result = js_runtime.mod_evaluate(mod_id);
    js_runtime.run_event_loop(Default::default()).await?;

    result.await?;

    Ok(())
}

// main.rs
fn main() {
    let args: Vec<String> = std::env::args().collect();
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();

    let http_fhir_client = FHIRHttpClient::<Option<String>>::new(
        FHIRHttpState::new(&args[1], None).expect("Failed to create FHIR client"),
    );

    if let Err(error) = runtime.block_on(run_js(None, http_fhir_client, "./example.ts")) {
        eprintln!("error: {}", error);
    }
}
