name: Release Docker
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  SERVER_IMAGE_NAME: hastehealth/hastehealth
  ADMIN_APP_IMAGE_NAME: hastehealth/admin-app

jobs:
  server:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: "write"
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $ --password-stdin
      - uses: "google-github-actions/auth@v3"
        with:
          project_id: ${{ vars.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"
      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ vars.GAR_LOCATION }}-docker.pkg.dev
      - name: Build and Publish Image
        run: |
          IMAGE_NAME=$(echo $SERVER_IMAGE_NAME | tr '[A-Z]' '[a-z]')
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          GCP_IMAGE_ID=${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{vars.GAR_REPOSITORY}}/hastehealth

          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          GCP_IMAGE_ID=$(echo $GCP_IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$GITHUB_REF_NAME

          # --platform linux/amd64,linux/arm64 \
          docker buildx build . \
           --file=docker/haste-health.dockerfile \
           --platform linux/amd64 \
           --tag "$GCP_IMAGE_ID:latest \
           --tag "$GCP_IMAGE_ID:$GITHUB_REF_NAME \
           --tag $IMAGE_ID:$GITHUB_REF_NAME \
           --tag $IMAGE_ID:latest \
           --label "runnumber=${GITHUB_RUN_ID}" \
           --push

  admin-app:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u $ --password-stdin
      - name: Build and Publish Image
        run: |
          IMAGE_NAME=$(echo $ADMIN_APP_IMAGE_NAME | tr '[A-Z]' '[a-z]')
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$GITHUB_REF_NAME

          # --platform linux/amd64,linux/arm64 \
          docker buildx build . \
           --file=docker/admin-app/dockerfile \
           --platform linux/amd64 \
           --tag $IMAGE_ID:$GITHUB_REF_NAME \
           --tag $IMAGE_ID:latest \
           --label "runnumber=${GITHUB_RUN_ID}" \
           --push
