name: GCP Testing

on:
  push:
    branches: ["main"]

jobs:
  gcp_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: "google-github-actions/auth@v3"
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
