name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  # Release unpublished packages.
  crate-io-release:
    environment: production
    name: Crates IO release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - &install-rust
        name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          config: ./backend/release-plz.toml
          manifest_path: ./backend/Cargo.toml
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  # crate-version-pr:
  #   environment: production
  #   name: Crates Version PR
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   concurrency:
  #     group: release-plz-${{ github.ref }}
  #     cancel-in-progress: false
  #   steps:
  #     - *checkout
  #     - *install-rust
  #     - name: Run release-plz
  #       uses: release-plz/action@v0.5
  #       with:
  #         config: ./backend/release-plz.toml
  #         manifest_path: ./backend/Cargo.toml
  #         command: release-pr
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  npm:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: "./frontend/pnpm-lock.yaml"
          node-version: 23
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Build dependencies
        run: pnpm ci:build
        working-directory: ./frontend

      - name: Create and publish versions
        run: pnpm ci:publish
        working-directory: ./frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
